# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('abbr', models.CharField(db_column='Abbr', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_column='Date')),
                ('examupdated', models.NullBooleanField(db_column='ExamUpdated')),
                ('examupdateddt', models.DateTimeField(blank=True, db_column='ExamUpdatedDT', null=True)),
                ('examposted', models.NullBooleanField(db_column='ExamPosted')),
                ('examposteddt', models.DateTimeField(blank=True, db_column='ExamPostedDT', null=True)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
                ('results', models.TextField(blank=True, db_column='Results', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datesexamlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateid', models.IntegerField(db_column='DateId')),
                ('examid', models.IntegerField(db_column='ExamId')),
                ('mmid', models.IntegerField(blank=True, db_column='MMId', null=True)),
                ('result_n', models.TextField(blank=True, db_column='Result_N', null=True)),
                ('result_t', models.TextField(blank=True, db_column='Result_T', null=True)),
                ('updated', models.NullBooleanField(db_column='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Examination0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofexam', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=8192, null=True)),
                ('comments', models.CharField(blank=True, max_length=8192, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Examminmax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmid', models.IntegerField(blank=True, db_column='MMId', null=True)),
                ('mfa', models.IntegerField(db_column='MFA')),
                ('minvalue', models.TextField(blank=True, db_column='MinValue', null=True)),
                ('maxvalue', models.TextField(blank=True, db_column='MaxValue', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='Name', unique=True)),
                ('sname', models.CharField(db_column='SName', max_length=25)),
                ('groupexam_id', models.IntegerField(db_column='GroupExam_Id')),
                ('mm_id', models.IntegerField(db_column='MM_Id')),
                ('min', models.TextField(blank=True, db_column='Min', null=True)),
                ('max', models.TextField(blank=True, db_column='Max', null=True)),
                ('comments', models.CharField(blank=True, db_column='Comments', max_length=250, null=True)),
                ('is_numeric', models.NullBooleanField(db_column='Is_Numeric')),
                ('is_text', models.NullBooleanField(db_column='Is_Text')),
                ('is_memo', models.NullBooleanField(db_column='Is_Memo')),
            ],
        ),
        migrations.CreateModel(
            name='Examschema',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=150, null=True, unique=True)),
                ('sequence', models.CharField(blank=True, db_column='Sequence', max_length=50, null=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examschemadet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('groupexamid', models.IntegerField(db_column='GroupExamId')),
                ('aa', models.IntegerField(db_column='AA')),
                ('examschemaid', models.ForeignKey(db_column='ExamSchemaid', on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.Examschema')),
            ],
        ),
        migrations.CreateModel(
            name='Groupexam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('sname', models.CharField(db_column='SName', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Groupmm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('sname', models.CharField(blank=True, db_column='SName', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keystable',
            fields=[
                ('table', models.CharField(db_column='Table', max_length=20, primary_key=True, serialize=False)),
                ('currentkey', models.IntegerField(db_column='CurrentKey')),
                ('updated', models.DateTimeField(blank=True, db_column='Updated', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50, unique=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=60, null=True)),
                ('mail', models.CharField(blank=True, db_column='Mail', max_length=50, null=True)),
                ('tk', models.CharField(blank=True, db_column='TK', max_length=5, null=True)),
                ('text', models.TextField(blank=True, db_column='Text', null=True)),
                ('hospital', models.NullBooleanField(db_column='Hospital')),
                ('medicalcenter', models.NullBooleanField(db_column='MedicalCenter')),
                ('eopyy', models.NullBooleanField(db_column='EOPYY')),
                ('contact', models.TextField(blank=True, db_column='CONTACT', null=True)),
                ('countryid', models.ForeignKey(db_column='CountryId', on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Mfa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromage', models.IntegerField(db_column='FromAge')),
                ('toage', models.IntegerField(db_column='ToAge')),
                ('sex', models.IntegerField(db_column='SEX')),
            ],
        ),
        migrations.CreateModel(
            name='Mm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('sname', models.CharField(blank=True, db_column='SName', max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mm2Mm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromid', models.IntegerField(db_column='Fromid')),
                ('toid', models.IntegerField(db_column='Toid')),
                ('text', models.CharField(blank=True, db_column='Text', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('surname', models.CharField(db_column='Surname', max_length=50)),
                ('dateofbirth', models.DateField(blank=True, db_column='DateOfBirth', null=True)),
                ('nationality', models.CharField(blank=True, db_column='Nationality', max_length=20, null=True)),
                ('idoncontry', models.CharField(blank=True, db_column='IdOnContry', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=20, null=True)),
                ('mail', models.CharField(blank=True, db_column='Mail', max_length=50, null=True)),
                ('ispatient', models.NullBooleanField(db_column='IsPatient')),
                ('isdoctor', models.NullBooleanField(db_column='IsDoctor')),
                ('canlogin', models.NullBooleanField(db_column='CanLogin')),
                ('accessonlyhisfile', models.NullBooleanField(db_column='AccessOnlyHisFile')),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=8192, null=True)),
                ('photo', models.BinaryField(blank=True, db_column='Photo', null=True)),
                ('countryid', models.ForeignKey(db_column='CountryId', on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SqliteSpFunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SqliteStat1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbl', models.TextField(blank=True, null=True)),
                ('idx', models.TextField(blank=True, null=True)),
                ('stat', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SqliteVsLinksNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('alias', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SqliteVsProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parenttype', models.TextField(blank=True, db_column='parentType', null=True)),
                ('parentname', models.TextField(blank=True, db_column='parentName', null=True)),
                ('propertyname', models.TextField(blank=True, db_column='propertyName', null=True)),
                ('propertyvalue', models.TextField(blank=True, db_column='propertyValue', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='examminmax',
            name='examid',
            field=models.ForeignKey(db_column='ExamId', on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.Examname'),
        ),
        migrations.AddField(
            model_name='examination0',
            name='categorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.ExaminationCategory'),
        ),
        migrations.AddField(
            model_name='examination0',
            name='peopleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.People'),
        ),
        migrations.AddField(
            model_name='dates',
            name='locationid',
            field=models.ForeignKey(db_column='LocationId', on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.Locations'),
        ),
        migrations.AddField(
            model_name='dates',
            name='peopleid',
            field=models.ForeignKey(db_column='PeopleId', on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.People'),
        ),
    ]
