# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BioExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofexam', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=8192, null=True)),
                ('comments', models.CharField(blank=True, max_length=8192, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BioExaminationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='BioExaminationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='\u03a4\u03b9\u03bc\u03ae')),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('BioExaminationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.BioExamination')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u03a7\u03ce\u03c1\u03b1')),
                ('abbr', models.CharField(max_length=2, verbose_name='\u03a7\u03ce\u03c1\u03b1(2)')),
                ('telephoneext', models.CharField(max_length=4, verbose_name='\u03a4\u03b7\u03bb')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Examination0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofexam', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=8192, null=True)),
                ('comments', models.CharField(blank=True, max_length=8192, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Examname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='Name', unique=True)),
                ('sname', models.CharField(db_column='SName', max_length=25)),
                ('groupexam_id', models.IntegerField(db_column='GroupExam_Id')),
                ('mm_id', models.IntegerField(db_column='MM_Id')),
                ('min', models.TextField(blank=True, db_column='Min', null=True)),
                ('max', models.TextField(blank=True, db_column='Max', null=True)),
                ('comments', models.CharField(blank=True, db_column='Comments', max_length=250, null=True)),
                ('is_numeric', models.NullBooleanField(db_column='Is_Numeric')),
                ('is_text', models.NullBooleanField(db_column='Is_Text')),
                ('is_memo', models.NullBooleanField(db_column='Is_Memo')),
                ('bioexaminationcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.BioExaminationCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Examschema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('sequence', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50, unique=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=60, null=True)),
                ('mail', models.CharField(blank=True, db_column='Mail', max_length=50, null=True)),
                ('tk', models.CharField(blank=True, db_column='TK', max_length=5, null=True)),
                ('text', models.TextField(blank=True, db_column='Text', null=True)),
                ('hospital', models.NullBooleanField(db_column='Hospital')),
                ('medicalcenter', models.NullBooleanField(db_column='MedicalCenter')),
                ('eopyy', models.NullBooleanField(db_column='EOPYY')),
                ('contact', models.TextField(blank=True, db_column='CONTACT', null=True)),
                ('countryid', models.ForeignKey(db_column='CountryId', on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateof', models.DateField()),
                ('datestart', models.DateField()),
                ('dateend', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=8192, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Mm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('sname', models.CharField(blank=True, db_column='SName', max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateof', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=8192, null=True)),
                ('comments', models.CharField(blank=True, max_length=8192, null=True)),
                ('categorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.OperationCategory')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=30, verbose_name='\u038c\u03bd\u03bf\u03bc\u03b1')),
                ('surname', models.CharField(db_column='Surname', max_length=50, verbose_name='\u0395\u03c0\u03ce\u03bd\u03c5\u03bc\u03bf')),
                ('dateofbirth', models.DateField(blank=True, db_column='DateOfBirth', null=True, verbose_name='\u0397\u03bc\u03b5\u03c1\u03bf\u03bc\u03b7\u03bd\u03af\u03b1 \u0393\u03ad\u03bd\u03bd\u03b7\u03c3\u03b7\u03c2')),
                ('nationality', models.CharField(blank=True, db_column='Nationality', max_length=20, null=True, verbose_name='\u03a5\u03c0\u03b7\u03ba\u03bf\u03cc\u03c4\u03b7\u03c4\u03b1')),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=60, null=True, verbose_name='\u03a4\u03b7\u03bb\u03b5\u03c6\u03c9\u03bd\u03bf')),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=60, null=True, verbose_name='FAX')),
                ('mobile', models.CharField(blank=True, db_column='mobile', max_length=60, null=True, verbose_name='\u039a\u03b9\u03bd\u03b7\u03c4\u03cc')),
                ('mail', models.CharField(blank=True, db_column='Mail', max_length=250, null=True)),
                ('ispatient', models.NullBooleanField(db_column='IsPatient', verbose_name='\u0391\u03c3\u03b8\u03b5\u03bd\u03ae\u03c2')),
                ('isdoctor', models.NullBooleanField(db_column='IsDoctor', verbose_name='\u0393\u03b9\u03b1\u03c4\u03c1\u03cc\u03c2')),
                ('canlogin', models.NullBooleanField(db_column='CanLogin')),
                ('accessonlyhisfile', models.NullBooleanField(db_column='AccessOnlyHisFile')),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=8192, null=True)),
                ('photo', models.BinaryField(blank=True, db_column='Photo', null=True)),
                ('countryid', models.ForeignKey(db_column='CountryId', on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.Country', verbose_name='\u03a7\u03ce\u03c1\u03b1')),
            ],
            options={
                'ordering': ('surname', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SpecialUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=100)),
                ('altpeopleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpecialUserAltPeople', to='DjgLeoApp001.People', verbose_name='Alt.\u0386\u03bd\u03b8\u03c1\u03c9\u03c0\u03bf\u03c2')),
                ('doctors', models.ManyToManyField(related_name='SpecialUserAltDoctors', to='DjgLeoApp001.People', verbose_name='\u0393\u03b9\u03b1\u03c4\u03c1\u03bf\u03af')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.Locations', verbose_name='\u03a4\u03cc\u03c0\u03bf\u03c2')),
                ('peopleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.People', verbose_name='\u0386\u03bd\u03b8\u03c1\u03c9\u03c0\u03bf\u03c2')),
                ('peoples', models.ManyToManyField(related_name='SpecialUserAltPeoples', to='DjgLeoApp001.People', verbose_name='\u0386\u03bd\u03b8\u03c1\u03c9\u03c0\u03bf\u03b9')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='operations',
            name='doctorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OperationDoctor', to='DjgLeoApp001.People'),
        ),
        migrations.AddField(
            model_name='operations',
            name='peopleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.People'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='categorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.MedicineCategory'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='doctorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicineDoctor', to='DjgLeoApp001.People'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='peopleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.People'),
        ),
        migrations.AddField(
            model_name='locations',
            name='peoples',
            field=models.ManyToManyField(to='DjgLeoApp001.People'),
        ),
        migrations.AddField(
            model_name='examination0',
            name='categorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.ExaminationCategory'),
        ),
        migrations.AddField(
            model_name='examination0',
            name='doctorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Examination0Doctor', to='DjgLeoApp001.People'),
        ),
        migrations.AddField(
            model_name='examination0',
            name='peopleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.People'),
        ),
        migrations.AddField(
            model_name='bioexaminationdetail',
            name='examnameid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.Examname', verbose_name='\u0395\u03be\u03ad\u03c4\u03b1\u03c3\u03b7'),
        ),
        migrations.AddField(
            model_name='bioexamination',
            name='categorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.ExaminationCategory'),
        ),
        migrations.AddField(
            model_name='bioexamination',
            name='doctorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExaminationBioDoctor', to='DjgLeoApp001.People'),
        ),
        migrations.AddField(
            model_name='bioexamination',
            name='examsschema',
            field=models.ManyToManyField(to='DjgLeoApp001.Examschema'),
        ),
        migrations.AddField(
            model_name='bioexamination',
            name='peopleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.People'),
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together=set([('peopleid', 'doctorid', 'categorid', 'dateof')]),
        ),
        migrations.AlterUniqueTogether(
            name='bioexaminationdetail',
            unique_together=set([('BioExaminationId', 'examnameid')]),
        ),
    ]
