# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjgLeoApp001', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ('name', 'surname')},
        ),
        migrations.AddField(
            model_name='locations',
            name='location',
            field=models.ManyToManyField(to='DjgLeoApp001.People'),
        ),
    ]
