# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DjgLeoApp001', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ('surname', 'name')},
        ),
        migrations.AddField(
            model_name='specialusers',
            name='altpeopleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SpecialUserAltPeople', to='DjgLeoApp001.People', verbose_name='Alt.\u0386\u03bd\u03b8\u03c1\u03c9\u03c0\u03bf\u03c2'),
        ),
        migrations.AddField(
            model_name='specialusers',
            name='doctors',
            field=models.ManyToManyField(related_name='SpecialUserAltDoctors', to='DjgLeoApp001.People', verbose_name='\u0393\u03b9\u03b1\u03c4\u03c1\u03bf\u03af'),
        ),
        migrations.AddField(
            model_name='specialusers',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.Locations', verbose_name='\u03a4\u03cc\u03c0\u03bf\u03c2'),
        ),
        migrations.AddField(
            model_name='specialusers',
            name='peopleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.People', verbose_name='\u0386\u03bd\u03b8\u03c1\u03c9\u03c0\u03bf\u03c2'),
        ),
        migrations.AddField(
            model_name='specialusers',
            name='peoples',
            field=models.ManyToManyField(related_name='SpecialUserAltPeoples', to='DjgLeoApp001.People', verbose_name='\u0386\u03bd\u03b8\u03c1\u03c9\u03c0\u03bf\u03b9'),
        ),
        migrations.AddField(
            model_name='specialusers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
