# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjgLeoApp001', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bioexaminationdetail',
            options={'ordering': ('BioExaminationId', 'id')},
        ),
        migrations.AlterModelOptions(
            name='examination0',
            options={'ordering': ('-dateofexam',)},
        ),
        migrations.AlterField(
            model_name='locations',
            name='peoples',
            field=models.ManyToManyField(blank=True, null=True, to='DjgLeoApp001.People'),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(blank=True, db_column='Phone', max_length=60, null=True, verbose_name='\u03a4\u03b7\u03bb\u03ad\u03c6\u03c9\u03bd\u03bf'),
        ),
    ]
