# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjgLeoApp001', '0002_auto_20170120_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='location',
            new_name='peoples',
        ),
    ]
