# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjgLeoApp001', '0002_auto_20170203_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
