# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjgLeoApp001', '0002_auto_20170218_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioexamination',
            name='categorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.ExaminationCategory', verbose_name='\u039a\u03b1\u03c4\u03b7\u03b3\u03bf\u03c1\u03af\u03b1'),
        ),
        migrations.AlterField(
            model_name='bioexamination',
            name='comments',
            field=models.CharField(blank=True, max_length=8192, null=True, verbose_name='\u03a3\u03c7\u03cc\u03bb\u03b9\u03b1'),
        ),
        migrations.AlterField(
            model_name='bioexamination',
            name='dateofexam',
            field=models.DateField(verbose_name='\u0397\u03bc\u03b5\u03c1\u03bf\u03bc\u03b7\u03bd\u03af\u03b1 \u0395\u03be\u03ad\u03c4\u03b1\u03c3\u03b7\u03c2'),
        ),
        migrations.AlterField(
            model_name='bioexamination',
            name='doctorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExaminationBioDoctor', to='DjgLeoApp001.People', verbose_name='\u0393\u03b9\u03b1\u03c4\u03c1\u03cc\u03c2'),
        ),
        migrations.AlterField(
            model_name='bioexamination',
            name='examsschema',
            field=models.ManyToManyField(to='DjgLeoApp001.Examschema', verbose_name='\u03a3\u03c7\u03ae\u03bc\u03b1'),
        ),
        migrations.AlterField(
            model_name='bioexamination',
            name='notes',
            field=models.CharField(blank=True, max_length=8192, null=True, verbose_name='\u03a3\u03b7\u03bc\u03b5\u03b9\u03ce\u03c3\u03b5\u03b9\u03c2'),
        ),
        migrations.AlterField(
            model_name='bioexamination',
            name='peopleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.People', verbose_name='\u0391\u03c3\u03b8\u03b5\u03bd\u03ae\u03c2'),
        ),
        migrations.AlterField(
            model_name='examination0',
            name='categorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.ExaminationCategory', verbose_name='\u039a\u03b1\u03c4\u03b7\u03b3\u03bf\u03c1\u03af\u03b1'),
        ),
        migrations.AlterField(
            model_name='examination0',
            name='comments',
            field=models.CharField(blank=True, max_length=8192, null=True, verbose_name='\u03a3\u03c7\u03cc\u03bb\u03b9\u03b1'),
        ),
        migrations.AlterField(
            model_name='examination0',
            name='dateofexam',
            field=models.DateField(verbose_name='\u0397\u03bc\u03b5\u03c1\u03bf\u03bc\u03b7\u03bd\u03af\u03b1 \u0395\u03be\u03ad\u03c4\u03b1\u03c3\u03b7\u03c2'),
        ),
        migrations.AlterField(
            model_name='examination0',
            name='doctorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Examination0Doctor', to='DjgLeoApp001.People', verbose_name='\u0393\u03b9\u03b1\u03c4\u03c1\u03cc\u03c2'),
        ),
        migrations.AlterField(
            model_name='examination0',
            name='notes',
            field=models.CharField(blank=True, max_length=8192, null=True, verbose_name='\u03a3\u03b7\u03bc\u03b5\u03b9\u03ce\u03c3\u03b5\u03b9\u03c2'),
        ),
        migrations.AlterField(
            model_name='examination0',
            name='peopleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.People', verbose_name='\u0391\u03c3\u03b8\u03b5\u03bd\u03ae\u03c2'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='bioexaminationcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.BioExaminationCategory', verbose_name='\u039a\u03b1\u03c4\u03b7\u03b3\u03bf\u03c1\u03af\u03b1'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='is_memo',
            field=models.NullBooleanField(verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='is_numeric',
            field=models.NullBooleanField(verbose_name='Numeric'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='is_text',
            field=models.NullBooleanField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='max',
            field=models.TextField(blank=True, null=True, verbose_name='Max'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='min',
            field=models.TextField(blank=True, null=True, verbose_name='Min'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0394\u03b9\u03b5\u03cd\u03b8\u03c5\u03bd\u03c3\u03b7'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='contact',
            field=models.TextField(blank=True, null=True, verbose_name='\u03a3\u03cd\u03bd\u03b4\u03b5\u03c3\u03bc\u03bf\u03c2'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='countryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.Country', verbose_name='\u03a7\u03ce\u03c1\u03b1'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='eopyy',
            field=models.NullBooleanField(verbose_name='\u0395\u039f\u03a0\u03a0\u03a5'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='hospital',
            field=models.NullBooleanField(verbose_name='\u039d\u03bf\u03c3\u03bf\u03ba\u03bf\u03bc\u03b5\u03af\u03bf'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='medicalcenter',
            field=models.NullBooleanField(verbose_name='\u0399\u03b1\u03c4\u03c1\u03b9\u03ba\u03cc \u039a\u03ad\u03bd\u03c4\u03c1\u03bf'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u039f\u03bd\u03b1\u03bc\u03b1\u03c3\u03af\u03b1'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='peoples',
            field=models.ManyToManyField(blank=True, null=True, to='DjgLeoApp001.People', verbose_name='\u0391\u03c4\u03bf\u03bc\u03b1'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='phone',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='\u03a4\u03b7\u03bb\u03ad\u03c6\u03c9\u03bd\u03b1'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='\u03a3\u03c7\u03cc\u03bb\u03b9\u03b1'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='tk',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='TK'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='sname',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='SName'),
        ),
        migrations.AlterField(
            model_name='people',
            name='accessonlyhisfile',
            field=models.NullBooleanField(verbose_name='Access Only His File'),
        ),
        migrations.AlterField(
            model_name='people',
            name='canlogin',
            field=models.NullBooleanField(verbose_name='CanLogin'),
        ),
        migrations.AlterField(
            model_name='people',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True, verbose_name='\u0397\u03bc\u03b5\u03c1\u03bf\u03bc\u03b7\u03bd\u03af\u03b1 \u0393\u03ad\u03bd\u03bd\u03b7\u03c3\u03b7\u03c2'),
        ),
        migrations.AlterField(
            model_name='people',
            name='fax',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='FAX'),
        ),
        migrations.AlterField(
            model_name='people',
            name='mail',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='people',
            name='mobile',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='\u039a\u03b9\u03bd\u03b7\u03c4\u03cc'),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u038c\u03bd\u03bf\u03bc\u03b1'),
        ),
        migrations.AlterField(
            model_name='people',
            name='nationality',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u03a5\u03c0\u03b7\u03ba\u03bf\u03cc\u03c4\u03b7\u03c4\u03b1'),
        ),
        migrations.AlterField(
            model_name='people',
            name='notes',
            field=models.CharField(blank=True, max_length=8192, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='\u03a4\u03b7\u03bb\u03ad\u03c6\u03c9\u03bd\u03bf'),
        ),
        migrations.AlterField(
            model_name='people',
            name='photo',
            field=models.BinaryField(blank=True, null=True, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='people',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='\u0395\u03c0\u03ce\u03bd\u03c5\u03bc\u03bf'),
        ),
    ]
