# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjgLeoApp001', '0004_dates_doctorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination0',
            name='doctorid',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='Examination0Doctor', to='DjgLeoApp001.People'),
            preserve_default=False,
        ),
    ]
