# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjgLeoApp001', '0004_auto_20170219_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u039f\u03bd\u03bf\u03bc\u03b1\u03c3\u03af\u03b1')),
                ('sname', models.CharField(max_length=15, verbose_name='\u03a3\u03cd\u03bd\u03c4\u03bc\u03b7\u03c3\u03b7')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MMType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u039f\u03bd\u03bf\u03bc\u03b1\u03c3\u03af\u03b1')),
                ('sname', models.CharField(max_length=15, verbose_name='\u03a3\u03cd\u03bd\u03c4\u03bc\u03b7\u03c3\u03b7')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='bioexaminationdetail',
            options={'ordering': ('BioExaminationId', 'examnameid', 'id')},
        ),
        migrations.AlterModelOptions(
            name='mm',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='examname',
            name='groupexam_id',
        ),
        migrations.RemoveField(
            model_name='examname',
            name='mm_id',
        ),
        migrations.AddField(
            model_name='examname',
            name='mm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.MM', verbose_name='M.M.'),
        ),
        migrations.AlterField(
            model_name='bioexaminationcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u039f\u03bd\u03bf\u03bc\u03b1\u03c3\u03af\u03b1'),
        ),
        migrations.AlterField(
            model_name='bioexaminationcategory',
            name='sname',
            field=models.CharField(max_length=15, verbose_name='\u03a3\u03cd\u03bd\u03c4\u03bc\u03b7\u03c3\u03b7'),
        ),
        migrations.AlterField(
            model_name='bioexaminationdetail',
            name='BioExaminationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.BioExamination', verbose_name='\u0391\u03c6\u03bf\u03c1\u03ac'),
        ),
        migrations.AlterField(
            model_name='bioexaminationdetail',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='\u03a4\u03b9\u03bc\u03ae'),
        ),
        migrations.AlterField(
            model_name='country',
            name='abbr',
            field=models.CharField(max_length=2, unique=True, verbose_name='\u03a7\u03ce\u03c1\u03b1(2)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u03a7\u03ce\u03c1\u03b1'),
        ),
        migrations.AlterField(
            model_name='doctorspeciality',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u039f\u03bd\u03bf\u03bc\u03b1\u03c3\u03af\u03b1'),
        ),
        migrations.AlterField(
            model_name='doctorspeciality',
            name='sname',
            field=models.CharField(max_length=15, verbose_name='\u03a3\u03cd\u03bd\u03c4\u03bc\u03b7\u03c3\u03b7'),
        ),
        migrations.AlterField(
            model_name='examinationcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u039f\u03bd\u03bf\u03bc\u03b1\u03c3\u03af\u03b1'),
        ),
        migrations.AlterField(
            model_name='examinationcategory',
            name='sname',
            field=models.CharField(max_length=15, verbose_name='\u03a3\u03cd\u03bd\u03c4\u03bc\u03b7\u03c3\u03b7'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='\u03a3\u03c7\u03cc\u03bb\u03b9\u03b1'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='is_memo',
            field=models.NullBooleanField(verbose_name='\u0395\u03ba\u03c4\u03b5\u03bd\u03ad\u03c2 \u039a\u03b5\u03af\u03bc\u03b5\u03bd\u03bf'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='is_numeric',
            field=models.NullBooleanField(verbose_name='\u0391\u03c1\u03b9\u03b8\u03bc\u03b9\u03c4\u03b9\u03ba\u03cc'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='is_text',
            field=models.NullBooleanField(verbose_name='\u039a\u03b5\u03af\u03bc\u03b5\u03bd\u03bf'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='max',
            field=models.TextField(blank=True, null=True, verbose_name='\u039c\u03ad\u03b3\u03b9\u03c3\u03c4\u03bf'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='min',
            field=models.TextField(blank=True, null=True, verbose_name='\u0395\u03bb\u03ac\u03c7\u03b9\u03c3\u03c4\u03bf'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='name',
            field=models.TextField(unique=True, verbose_name='\u039f\u03bd\u03bf\u03bc\u03b1\u03c3\u03af\u03b1'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='sname',
            field=models.CharField(max_length=25, verbose_name='\u03a3\u03c5\u03bd\u03c4\u03bc\u03b7\u03c3\u03b7'),
        ),
        migrations.AlterField(
            model_name='examschema',
            name='name',
            field=models.CharField(default=0, max_length=150, unique=True, verbose_name='\u03a3\u03c7\u03ae\u03bc\u03b1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examschema',
            name='sequence',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u03a3\u03b5\u03b9\u03c1\u03ac'),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u039f\u03bd\u03bf\u03bc\u03b1\u03c3\u03af\u03b1'),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='sname',
            field=models.CharField(max_length=15, verbose_name='\u03a3\u03cd\u03bd\u03c4\u03bc\u03b7\u03c3\u03b7'),
        ),
        migrations.AlterField(
            model_name='mm',
            name='name',
            field=models.CharField(default=0, max_length=50, unique=True, verbose_name='\u039f\u03bd\u03bf\u03bc\u03b1\u03c3\u03af\u03b1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mm',
            name='sname',
            field=models.CharField(default=0, max_length=15, verbose_name='\u03a3\u03cd\u03bd\u03c4\u03bc\u03b7\u03c3\u03b7'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operationcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u039f\u03bd\u03bf\u03bc\u03b1\u03c3\u03af\u03b1'),
        ),
        migrations.AlterField(
            model_name='operationcategory',
            name='sname',
            field=models.CharField(max_length=15, verbose_name='\u03a3\u03cd\u03bd\u03c4\u03bc\u03b7\u03c3\u03b7'),
        ),
        migrations.AddField(
            model_name='examname',
            name='groupexam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.GroupExam', verbose_name='\u039f\u03bc\u03ac\u03b4\u03b1'),
        ),
        migrations.AddField(
            model_name='mm',
            name='mmtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.MMType', verbose_name='\u0395\u03af\u03b4\u03bf\u03c2'),
        ),
    ]
