# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjgLeoApp001', '0005_examination0_doctorid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ('surname', 'name')},
        ),
        migrations.AddField(
            model_name='people',
            name='mobile',
            field=models.CharField(blank=True, db_column='mobile', max_length=60, null=True, verbose_name='\u039a\u03b9\u03bd\u03b7\u03c4\u03cc'),
        ),
        migrations.AlterField(
            model_name='people',
            name='dateofbirth',
            field=models.DateField(blank=True, db_column='DateOfBirth', null=True, verbose_name='\u0397\u03bc\u03b5\u03c1\u03bf\u03bc\u03b7\u03bd\u03af\u03b1 \u0393\u03ad\u03bd\u03bd\u03b7\u03c3\u03b7\u03c2'),
        ),
        migrations.AlterField(
            model_name='people',
            name='fax',
            field=models.CharField(blank=True, db_column='Fax', max_length=60, null=True, verbose_name='FAX'),
        ),
        migrations.AlterField(
            model_name='people',
            name='isdoctor',
            field=models.NullBooleanField(db_column='IsDoctor', verbose_name='\u0393\u03b9\u03b1\u03c4\u03c1\u03cc\u03c2'),
        ),
        migrations.AlterField(
            model_name='people',
            name='ispatient',
            field=models.NullBooleanField(db_column='IsPatient', verbose_name='\u0391\u03c3\u03b8\u03b5\u03bd\u03ae\u03c2'),
        ),
        migrations.AlterField(
            model_name='people',
            name='mail',
            field=models.CharField(blank=True, db_column='Mail', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(db_column='Name', max_length=30, verbose_name='\u038c\u03bd\u03bf\u03bc\u03b1'),
        ),
        migrations.AlterField(
            model_name='people',
            name='nationality',
            field=models.CharField(blank=True, db_column='Nationality', max_length=20, null=True, verbose_name='\u03a5\u03c0\u03b7\u03ba\u03bf\u03cc\u03c4\u03b7\u03c4\u03b1'),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(blank=True, db_column='Phone', max_length=60, null=True, verbose_name='\u03a4\u03b7\u03bb\u03b5\u03c6\u03c9\u03bd\u03bf'),
        ),
        migrations.AlterField(
            model_name='people',
            name='surname',
            field=models.CharField(db_column='Surname', max_length=50, verbose_name='\u0395\u03c0\u03ce\u03bd\u03c5\u03bc\u03bf'),
        ),
    ]
