# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjgLeoApp001', '0005_auto_20170220_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bioexamination',
            options={'ordering': ('-dateofexam',)},
        ),
        migrations.AlterModelOptions(
            name='bioexaminationcategory',
            options={'ordering': ('name', 'sname')},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='doctorspeciality',
            options={'ordering': ('name', 'sname')},
        ),
        migrations.AlterModelOptions(
            name='examinationcategory',
            options={'ordering': ('name', 'sname')},
        ),
        migrations.AlterModelOptions(
            name='examname',
            options={'ordering': ('name', 'sname')},
        ),
        migrations.AlterModelOptions(
            name='examschema',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ('-dateof',)},
        ),
        migrations.AlterModelOptions(
            name='medicinecategory',
            options={'ordering': ('name', 'sname')},
        ),
        migrations.AlterModelOptions(
            name='operationcategory',
            options={'ordering': ('name', 'sname')},
        ),
        migrations.AlterModelOptions(
            name='operations',
            options={'ordering': ('dateof',)},
        ),
        migrations.AddField(
            model_name='examname',
            name='result_type',
            field=models.IntegerField(choices=[(1, '\u0391\u03c1\u03b9\u03b8\u03bc\u03b7\u03c4\u03b9\u03ba\u03cc'), (2, '\u039a\u03b5\u03af\u03bc\u03b5\u03bd\u03bf'), (3, '\u0391\u03c1\u03b9\u03b8\u03bc\u03b7\u03c4\u03b9\u03ba\u03cc + \u039a\u03b5\u03af\u03bc\u03b5\u03bd\u03bf'), (4, '\u0395\u03ba\u03c4\u03b5\u03bd\u03ad\u03c2 \u039a\u03b5\u03af\u03bc\u03b5\u03bd\u03bf')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examname',
            name='is_numeric',
            field=models.NullBooleanField(verbose_name='\u0391\u03c1\u03b9\u03b8\u03bc\u03b7\u03c4\u03b9\u03ba\u03cc'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='max',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='\u039c\u03ad\u03b3\u03b9\u03c3\u03c4\u03bf'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='min',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='\u0395\u03bb\u03ac\u03c7\u03b9\u03c3\u03c4\u03bf'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='mm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.MM', verbose_name='M.M.'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='name',
            field=models.TextField(max_length=10, unique=True, verbose_name='\u039f\u03bd\u03bf\u03bc\u03b1\u03c3\u03af\u03b1'),
        ),
    ]
