# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjgLeoApp001', '0006_auto_20170122_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='idoncontry',
        ),
    ]
