# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjgLeoApp001', '0006_auto_20170222_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='examname',
            name='maxvalue',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='\u039c\u03ad\u03b3\u03b9\u03c3\u03c4\u03bf'),
        ),
        migrations.AddField(
            model_name='examname',
            name='minvalue',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='\u0395\u03bb\u03ac\u03c7\u03b9\u03c3\u03c4\u03bf'),
        ),
        migrations.AlterField(
            model_name='examname',
            name='mm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.MM', verbose_name='M.M.'),
        ),
    ]
