# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjgLeoApp001', '0007_auto_20170222_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examname',
            name='max',
        ),
        migrations.RemoveField(
            model_name='examname',
            name='min',
        ),
        migrations.AlterField(
            model_name='examname',
            name='mm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.MM', verbose_name='M.M.'),
        ),
    ]
