# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjgLeoApp001', '0007_remove_people_idoncontry'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='telephoneext',
            field=models.CharField(db_column='telephoneext', default=24, max_length=4, verbose_name='\u03a4\u03b7\u03bb'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='abbr',
            field=models.CharField(db_column='Abbr', max_length=2, verbose_name='\u03a7\u03ce\u03c1\u03b1(2) '),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_column='Name', max_length=50, verbose_name='\u03a7\u03ce\u03c1\u03b1'),
        ),
    ]
