# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjgLeoApp001', '0010_auto_20170224_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examname',
            name='mm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.MM', verbose_name='M\u03bf\u03bd\u03ac\u03b4\u03b1 M\u03ad\u03c4\u03c1\u03b7\u03c3\u03b7\u03c2(Min/Max)'),
        ),
    ]
