# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjgLeoApp001', '0013_auto_20170425_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='VExamdetaisl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=8192, null=True)),
                ('comments', models.CharField(blank=True, max_length=8192, null=True)),
                ('dateofexam', models.DateField(verbose_name='\u0397\u03bc\u03b5\u03c1\u03bf\u03bc\u03b7\u03bd\u03af\u03b1 \u0395\u03be\u03ad\u03c4\u03b1\u03c3\u03b7\u03c2')),
                ('value', models.FloatField(blank=True, null=True)),
                ('notes01', models.CharField(blank=True, max_length=255, null=True)),
                ('bioexaminationid_id', models.IntegerField(blank=True, null=True)),
                ('examnameid_id', models.IntegerField(blank=True, null=True)),
                ('id02', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sname', models.CharField(blank=True, max_length=25, null=True)),
                ('comments01', models.CharField(blank=True, max_length=250, null=True)),
                ('bioexaminationcategory_id', models.IntegerField(blank=True, null=True)),
                ('mm_id', models.IntegerField(blank=True, null=True)),
                ('groupexam_id', models.IntegerField(blank=True, null=True)),
                ('result_type', models.IntegerField(blank=True, null=True)),
                ('maxvalue', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('minvalue', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'v_examdetaisl',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='examname',
            name='mm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjgLeoApp001.MM', verbose_name='M\u03bf\u03bd\u03ac\u03b4\u03b1 M\u03ad\u03c4\u03c1\u03b7\u03c3\u03b7\u03c2(Min/Max)'),
        ),
    ]
